# Generated by Django 5.0.1 on 2025-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'M-Pesa Access Token',
                'verbose_name_plural': 'M-Pesa Access Tokens',
                'db_table': 'mpesa_access_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KSh', max_digits=10)),
                ('phone_number', models.CharField(help_text='Phone number in format 2547XXXXXXXX', max_length=15)),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'M-Pesa Payment',
                'verbose_name_plural': 'M-Pesa Payments',
                'db_table': 'mpesa_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
