# Generated by Django 5.0.1 on 2025-11-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['-created_at'], name='mpesa_payme_created_e79497_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['status'], name='mpesa_payme_status_661e09_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesapayment',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_payme_checkou_d8fc6a_idx'),
        ),
    ]
